### ISSUE TITLE
How SideMenu is working

### ISSUE THREAD

**Issue by leandroz** [NativeScript/sample-Tasks#1]
I tried to build the app without any luck, but in what I am really interested on is the Side Menu, i want to know how to setup it and how is working. I am looking at the code but i can't see where is defined, where you defined the icon for the menu and so on. Could be great an explanation of each part of the app in the blog!

**Comment by dkallkro** [comment]
Hi, i am also looking to find an example were side-bar is implemented? are you working on that?

/Allan

**Comment by leandroz** [comment]
Not right now but is the idea, I will look for implementations for Android and for iOS and use the code for creating a NativeScript version, but I think that could be great to have the component out of the box as a component of NativeScript.
I read that Navbar will be an XML tag so maybe there will be a Sidebar or something like that too.

**Comment by valentinstoychev** [comment]
Hi - we are working on a series of blog posts explaining the entire functionality. The side bar components not available at the moment, but it will be included very shortly. Please let us know for any specific topics you want to see in the blog posts, I will gladly focus on them.

**Comment by dkallkro** [comment]
Hi valentinstoychev, any news on side menu and blog post. we seriously need some fully examples. We have startet building our first app in NativeScript. Some examples img is attached. We have until now build all UI, and will start to attach to our cloud very soon. The app has until now around 50 different pages and we need things to get it done. for example we need the sidebar, since it is a part of our navigation. Also some examples how to handle keyboard scenarios. (scroll page up so keyboards does not overlay fields) also closing keyboards. 

Best regards Allan

![img_0018 1](https://cloud.githubusercontent.com/assets/11520161/7132769/9fab8494-e28c-11e4-88d3-57864a650fc3.PNG)
![img_0019 1](https://cloud.githubusercontent.com/assets/11520161/7132773/a78c2470-e28c-11e4-83d3-5dc8761b5cac.PNG)

**Comment by leandroz** [comment]
@dkallkro now you have to write something about how was creating 50 pages with native script!
